name: Cypress Parallel Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Ou a versão do Node.js que você está usando

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests in Parallel
        run: npm run cy:parallel

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports

      - name: Archive Screenshots and Videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots-videos
          path: cypress/screenshots, cypress/videos